default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: kuzmich
  password: 1234567890

development:
  <<: *default
  host: localhost
  database: cable_chat_app

production:
  adapter: postgresql
  encoding: utf8
  pool: 15
  url:  <%= ENV["DATABASE_URL"] %>
  database: cable_chat_app
 

test:
  <<: *default
  host: localhost
  database: cable_app_test